# Map salary checking

- enrollment 11, 21
- submit oct 15 to dec 7
-scope -nov to dec

- field sales
- Tele Sales

In [23]:
# S:\ENROLLMENT\ENROLLMENT-PUBLIC\MEDICARE\MAP
# MAP Roster_2021


import pandas as pd
import os

# DualEligibleMembers.xlsx
#pd.read_excel('DualEligibleMembers.xlsx', index_col=0)

url = "S:\ENROLLMENT\ENROLLMENT-PUBLIC\MEDICARE\MAP\MAP Roster_2021.xlsx"

df1=pd.read_excel(
     os.path.join(url),
     engine='openpyxl',
     sheet_name='Enrollment Tracking'
)

df2=pd.read_excel(
     os.path.join(url),
     engine='openpyxl',
     sheet_name='Withdrawal Cancel Tracking'
)

df3=pd.read_excel(
     os.path.join(url),
     engine='openpyxl',
     sheet_name='Not Enrolled'
)

df4=pd.read_excel(
     os.path.join(url),
     engine='openpyxl',
     sheet_name='Enrolled'
)


print (list(df1.columns))

df1.head()

C:\Users\tflung\Downloads\WPy64-3870\python-3.8.7.amd64\lib\site-packages\openpyxl\worksheet\_reader.py:300: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

['Enrollment Status', 'Legacy ID', 'Member Last Name', 'Member First Name', 'Medicaid_ID', 'MBI', 'LOB', 'Overall Status', 'Overall Start Date', 'Overall End Date', 'Medicaid Status', 'Medicaid Start Date', 'Medicaid End Date', 'Medicare Status', 'Medicare Start Date', 'Medicare End Date', 'Referral/SOA Date', 'Referral/Lead Source', 'Sales Agent', 'Pushed to Intake Date', 'B- file Date', 'E-file Date', 'R-file Date', 'Rejection Code', 'Application Date', 'Application Received Date', 'Enrollment Mechanism', 'Election Period', 'SEP Reasons', 'Missing Information Reason', 'RFI Letter Sent Date', 'Missing Information Due Date', 'Missing Information Received Date', 'Submitted to CMS Date', 'DTRR (TC61) Date', 'Enrollment Confirmation Letter Sent Date', 'DTRR (Rejection) Date', 'DTRR Rejection Code', 'Rejection Letter Sent Date', 'Notes', 'Denial Letter Sent Date', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48']

,Enrollment Status,Legacy ID,Member Last Name,Member First Name,Medicaid_ID,MBI,LOB,Overall Status,Overall Start Date,Overall End Date,Medicaid Status,Medicaid Start Date,Medicaid End Date,Medicare Status,Medicare Start Date,Medicare End Date,Referral/SOA Date,Referral/Lead Source,Sales Agent,Pushed to Intake Date,B- file Date,E-file Date,R-file Date,Rejection Code,Application Date,Application Received Date,Enrollment Mechanism,Election Period,SEP Reasons,Missing Information Reason,RFI Letter Sent Date,Missing Information Due Date,Missing Information Received Date,Submitted to CMS Date,DTRR (TC61) Date,Enrollment Confirmation Letter Sent Date,DTRR (Rejection) Date,DTRR Rejection Code,Rejection Letter Sent Date,Notes,Denial Letter Sent Date,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48
0,Pending Assessment Date,23007.0,ABDULLAH,JAMILLAH,ZU47506E,1VQ9TX6CK38,MAP,Submitted to Enrollment,NaT,NaT,NaN,None,NaN,NaN,NaT,NaT,2020-12-07,Inbound Call,Katiria Fernandez (BD),NaT,NaT,NaT,NaT,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,35178.0,Abreu Abreu,Ramon D,RY78891P,1VV0KC1HK23,MAP,Prospect,NaT,NaT,NaN,None,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaT,NaT,NaT,NaT,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Pushed to Intake,112378.0,Abreu GRATEREAUX,Jose,SN91749K,8CP4G93JC91,MAP,Pending,2021-03-01,NaT,pending,2021-03-01 00:00:00,NaN,NaN,NaT,NaT,2021-02-05,Internal Lead/MLTC Member,Ivonne Cedeno Mendoza (BD),2021-02-05,NaT,NaT,NaT,NaN,NaT,NaT,NaN,M = MA-OEP,Enrolled in a Medicare Advantage plan and want...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,124592.0,Abuhashish,Shukriyya S,XA01125N,8P70TR4DH42,MAP,Prospect,NaT,NaT,NaN,None,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaT,NaT,NaT,NaT,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,79921.0,ACEVEDO,LUCIA,WS74987N,9J82GN3UP18,MAP,Pending,NaT,NaT,NaN,None,NaN,NaN,NaT,NaT,NaT,NaN,Hanan Youssef (IN),NaT,NaT,NaT,NaT,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# Rename
df1 = df1.rename(columns={'Overall Start Date': 'EnrollDate'})
df2 = df2.rename(columns={'Overall Start Date': 'EnrollDate'})
df3 = df3.rename(columns={'Overall Start Date': 'EnrollDate'})
df4 = df4.rename(columns={'Overall Start Date': 'EnrollDate'})

df1 = df1.rename(columns={'Sales Agent': 'Rep'})
df2 = df2.rename(columns={'Sales Agent': 'Rep'})
df3 = df3.rename(columns={'Sales Agent': 'Rep'})
df4 = df4.rename(columns={'Sales Agent': 'Rep'})

df1 = df1.rename(columns={'Referral/SOA Date': 'SOA'})
df2 = df2.rename(columns={'Referral/SOA Date': 'SOA'})
df3 = df3.rename(columns={'Referral/SOA Date': 'SOA'})
df4 = df4.rename(columns={'Referral/SOA Date': 'SOA'})

df1 = df1.rename(columns={'Application Date': 'AppDate'})
df2 = df2.rename(columns={'Application Date': 'AppDate'})
df3 = df3.rename(columns={'Application Date': 'AppDate'})
df4 = df4.rename(columns={'Application Date': 'AppDate'})

df1 = df1.rename(columns={'Overall Status': 'Status'})
df2 = df2.rename(columns={'Overall Status': 'Status'})
df3 = df3.rename(columns={'Overall Status': 'Status'})
df4 = df4.rename(columns={'Overall Status': 'Status'})

df1 = df1.rename(columns={'Legacy ID': 'ID'})
df2 = df2.rename(columns={'Legacy ID': 'ID'})
df3 = df3.rename(columns={'Legacy ID': 'ID'})
df4 = df4.rename(columns={'Legacy ID': 'ID'})

# select columns
df1 = df1[['ID', 'EnrollDate', 'LOB', 'Status', 'SOA', 'AppDate', 'Rep']]
df2 = df2[['ID', 'EnrollDate', 'LOB', 'Status', 'SOA', 'AppDate', 'Rep']]
df3 = df3[['ID', 'EnrollDate', 'LOB', 'Status', 'SOA', 'AppDate', 'Rep']]
df4 = df4[['ID', 'EnrollDate', 'LOB', 'Status', 'SOA', 'AppDate', 'Rep']]

# Jan Feb enrollment
df1 = df1[(df1['EnrollDate'] == '2021-01-01') | (df1['EnrollDate'] == '2021-02-01')]
df2 = df2[(df2['EnrollDate'] == '2021-01-01') | (df2['EnrollDate'] == '2021-02-01')]
df3 = df3[(df3['EnrollDate'] == '2021-01-01') | (df3['EnrollDate'] == '2021-02-01')]
df4 = df4[(df4['EnrollDate'] == '2021-01-01') | (df4['EnrollDate'] == '2021-02-01')]

# SOA
df1 = df1[(df1['SOA'] >= '2020-11-01') & (df1['SOA'] <= '2020-12-31')]
df2 = df2[(df2['SOA'] >= '2020-11-01') & (df2['SOA'] <= '2020-12-31')]
df3 = df3[(df3['SOA'] >= '2020-11-01') & (df3['SOA'] <= '2020-12-31')]
df4 = df4[(df4['SOA'] >= '2020-11-01') & (df4['SOA'] <= '2020-12-31')]

print (df1.count())
print (df2.count())
print (df3.count())
print (df4.count())

ID            0
EnrollDate    0
LOB           0
Status        0
SOA           0
AppDate       0
Rep           0
dtype: int64
ID            7
EnrollDate    7
LOB           7
Status        7
SOA           7
AppDate       6
Rep           7
dtype: int64
ID            7
EnrollDate    7
LOB           7
Status        7
SOA           7
AppDate       3
Rep           7
dtype: int64
ID            179
EnrollDate    179
LOB           179
Status        179
SOA           179
AppDate       179
Rep           179
dtype: int64

In [25]:
# Whole Team - Enrolled

df1 = df1[(df1['Rep'] == 'Yanery Fernandez') 
          | (df1['Rep'] == 'Ivonne Cedeno Mendoza (BD)')
          | (df1['Rep'] == 'James (Shiou-Hao) Lu')
          | (df1['Rep'] == 'Monalisa Crossway')
          | (df1['Rep'] == 'Laura Lou Seefeldt (BD)')
          | (df1['Rep'] == 'Griselle Leonardo (BD)')
          | (df1['Rep'] == 'Shelly Bobb (BD)')
          | (df1['Rep'] == 'Zhen Zhu')
          | (df1['Rep'] == 'Confessor Concepcion')
          | (df1['Rep'] == 'Keith Douglas')
          | (df1['Rep'] == 'Angela Hernandez')
          | (df1['Rep'] == 'Carolina Zuluaga (BD)') 
          | (df1['Rep'] == 'Katiria Fernandez (BD)')
          | (df1['Rep'] == 'Brad Willinger (BD)')
          | (df1['Rep'] == 'Vincent Lee (BD)')
          | (df1['Rep'] == 'Robert Echevarria ')]

# Whole Team - Enrolled

df2 = df2[(df2['Rep'] == 'Yanery Fernandez') 
          | (df2['Rep'] == 'Ivonne Cedeno Mendoza (BD)')
          | (df2['Rep'] == 'James (Shiou-Hao) Lu')
          | (df2['Rep'] == 'Monalisa Crossway')
          | (df2['Rep'] == 'Laura Lou Seefeldt (BD)')
          | (df2['Rep'] == 'Griselle Leonardo (BD)')
          | (df2['Rep'] == 'Shelly Bobb (BD)')
          | (df2['Rep'] == 'Zhen Zhu')
          | (df2['Rep'] == 'Confessor Concepcion')
          | (df2['Rep'] == 'Keith Douglas')
          | (df2['Rep'] == 'Angela Hernandez')
          | (df2['Rep'] == 'Carolina Zuluaga (BD)') 
          | (df2['Rep'] == 'Katiria Fernandez (BD)')
          | (df2['Rep'] == 'Brad Willinger (BD)')
          | (df2['Rep'] == 'Vincent Lee (BD)')
          | (df2['Rep'] == 'Robert Echevarria ')]

# Whole Team - Enrolled

df3 = df3[(df3['Rep'] == 'Yanery Fernandez') 
          | (df3['Rep'] == 'Ivonne Cedeno Mendoza (BD)')
          | (df3['Rep'] == 'James (Shiou-Hao) Lu')
          | (df3['Rep'] == 'Monalisa Crossway')
          | (df3['Rep'] == 'Laura Lou Seefeldt (BD)')
          | (df3['Rep'] == 'Griselle Leonardo (BD)')
          | (df3['Rep'] == 'Shelly Bobb (BD)')
          | (df3['Rep'] == 'Zhen Zhu')
          | (df3['Rep'] == 'Confessor Concepcion')
          | (df3['Rep'] == 'Keith Douglas')
          | (df3['Rep'] == 'Angela Hernandez')
          | (df3['Rep'] == 'Carolina Zuluaga (BD)') 
          | (df3['Rep'] == 'Katiria Fernandez (BD)')
          | (df3['Rep'] == 'Brad Willinger (BD)')
          | (df3['Rep'] == 'Vincent Lee (BD)')
          | (df3['Rep'] == 'Robert Echevarria ')]

# Whole Team - Enrolled

df4 = df4[(df4['Rep'] == 'Yanery Fernandez') 
          | (df4['Rep'] == 'Ivonne Cedeno Mendoza (BD)')
          | (df4['Rep'] == 'James (Shiou-Hao) Lu')
          | (df4['Rep'] == 'Monalisa Crossway')
          | (df4['Rep'] == 'Laura Lou Seefeldt (BD)')
          | (df4['Rep'] == 'Griselle Leonardo (BD)')
          | (df4['Rep'] == 'Shelly Bobb (BD)')
          | (df4['Rep'] == 'Zhen Zhu')
          | (df4['Rep'] == 'Confessor Concepcion')
          | (df4['Rep'] == 'Keith Douglas')
          | (df4['Rep'] == 'Angela Hernandez')
          | (df4['Rep'] == 'Carolina Zuluaga (BD)') 
          | (df4['Rep'] == 'Katiria Fernandez (BD)')
          | (df4['Rep'] == 'Brad Willinger (BD)')
          | (df4['Rep'] == 'Vincent Lee (BD)')
          | (df4['Rep'] == 'Robert Echevarria ')]

print (df1.count())
print (df2.count())
print (df3.count())
print (df4.count())

ID            0
EnrollDate    0
LOB           0
Status        0
SOA           0
AppDate       0
Rep           0
dtype: int64
ID            4
EnrollDate    4
LOB           4
Status        4
SOA           4
AppDate       3
Rep           4
dtype: int64
ID            3
EnrollDate    3
LOB           3
Status        3
SOA           3
AppDate       1
Rep           3
dtype: int64
ID            37
EnrollDate    37
LOB           37
Status        37
SOA           37
AppDate       37
Rep           37
dtype: int64

In [27]:
print(df1)
print()
print('Enrollment Tracking')
df5 = df1.groupby(["LOB", "Rep"])["Rep"].count().reset_index(name="count")
print (df5)
print('total=')
print(df1.count().Rep)
print()

print(df2)
print()
print('Withdrawal Cancel Tracking')
df6 = df2.groupby(["LOB", "Rep"])["Rep"].count().reset_index(name="count")
print (df6)
print('total=')
print(df2.count().Rep)
print()

print(df3)
print()
print('Not Enrolled')
df7 = df3.groupby(["LOB", "Rep"])["Rep"].count().reset_index(name="count")
print (df7)
print('total=')
print(df3.count().Rep)

print()
print(df4)
print()
print('Enrolled')
df8 = df4.groupby(["LOB", "Rep"])["Rep"].count().reset_index(name="count")
print (df8)
print('total=')
print(df4.count().Rep)

Empty DataFrame
Columns: [ID, EnrollDate, LOB, Status, SOA, AppDate, Rep]
Index: []

Enrollment Tracking
Empty DataFrame
Columns: [LOB, Rep, count]
Index: []
total=
0

         ID EnrollDate  LOB    Status        SOA    AppDate  \
2  112464.0 2021-02-01  MAP  Enrolled 2020-11-25 2021-01-20
3  112466.0 2021-02-01  MAP  Enrolled 2020-11-25 2021-01-20
5  122194.0 2021-02-01  MAP   Pending 2020-12-01        NaT
6  112598.0 2021-02-01  MAP  Enrolled 2020-11-09 2021-01-07

                          Rep
2  Ivonne Cedeno Mendoza (BD)
3  Ivonne Cedeno Mendoza (BD)
5      Griselle Leonardo (BD)
6       Carolina Zuluaga (BD)

Withdrawal Cancel Tracking
   LOB                         Rep  count
0  MAP       Carolina Zuluaga (BD)      1
1  MAP      Griselle Leonardo (BD)      1
2  MAP  Ivonne Cedeno Mendoza (BD)      2
total=
4

          ID EnrollDate  LOB     Status        SOA    AppDate  \
4   123506.0 2021-01-01  MAP  Withdrawn 2020-11-27        NaT
16   18461.0 2021-02-01  MAP  Withdrawn 2020-11-24        NaT
27  101451.0 2021-02-01  MAP     Denied 2020-11-19 2021-01-22

                        Rep
4   Laura Lou Seefeldt (BD)
16  Laura Lou Seefeldt (BD)
27         Shelly Bobb (BD)

Not Enrolled
   LOB                      Rep  count
0  MAP  Laura Lou Seefeldt (BD)      2
1  MAP         Shelly Bobb (BD)      1
total=
3

         ID EnrollDate  LOB    Status        SOA    AppDate  \
72    15013 2021-01-01  MAP  Enrolled 2020-11-17 2020-12-01
106   42476 2021-01-01  MAP  Enrolled 2020-11-04 2020-11-30
117    1232 2021-01-01  MAP  Enrolled 2020-11-27 2020-12-07
171  116273 2021-02-01  MAP  Enrolled 2020-11-09 2021-01-05
172  127927 2021-02-01  MAP  Enrolled 2020-12-22 2021-01-14
175  134937 2021-02-01  MAP  Enrolled 2020-11-19 2021-01-05
182  119562 2021-02-01  MAP  Enrolled 2020-11-28 2021-01-06
183   70146 2021-02-01  MAP  Enrolled 2020-11-25 2021-01-06
185   97445 2021-02-01  MAP  Enrolled 2020-11-28 2021-01-19
207  116544 2021-02-01  MAP  Enrolled 2020-12-06 2021-01-07
209  141260 2021-02-01  MAP  Enrolled 2020-11-14 2021-01-05
214  127208 2021-02-01  MAP  Enrolled 2020-12-04 2021-01-08
216   85676 2021-02-01  MAP  Enrolled 2020-11-25 2021-01-07
220  137358 2021-02-01  MAP  Enrolled 2020-12-12 2020-01-11
223  111357 2021-02-01  MAP  Enrolled 2020-11-29 2021-01-07
230   37468 2021-02-01  MAP  Enrolled 2020-11-25 2021-01-19
232    3705 2021-02-01  MAP  Enrolled 2020-11-20 2021-01-19
240   66110 2021-02-01  MAP  Enrolled 2020-12-23 2021-01-20
242   91911 2021-02-01  MAP  Enrolled 2020-11-25 2021-01-21
245   21451 2021-02-01  MAP  Enrolled 2020-12-31 2021-01-21
246   82153 2021-02-01  MAP  Enrolled 2020-12-03 2021-01-21
247  114181 2021-02-01  MAP  Enrolled 2020-12-04 2021-01-20
248   93711 2021-02-01  MAP  Enrolled 2020-11-24 2021-01-22
249  109254 2021-02-01  MAP  Enrolled 2020-11-25 2021-01-22
252   42476 2021-01-01  MAP  Enrolled 2020-11-04 2021-01-25
253  134126 2021-02-01  MAP  Enrolled 2020-12-07 2021-01-27
254   98827 2021-02-01  MAP  Enrolled 2020-11-18 2021-01-22
257  126346 2021-02-01  MAP  Enrolled 2020-11-27 2021-01-27
258  103614 2021-02-01  MAP  Enrolled 2020-12-01 2021-01-25
261  110119 2021-02-01  MAP  Enrolled 2020-11-24 2021-01-25
262  139735 2021-02-01  MAP  Enrolled 2020-12-02 2021-01-22
266  115411 2021-02-01  MAP  Enrolled 2020-12-07 2021-01-22
267  126471 2021-02-01  MAP  Enrolled 2020-12-05 2021-01-27
269  134401 2021-02-01  MAP  Enrolled 2020-11-24 2021-01-25
272  113855 2021-02-01  MAP  Enrolled 2020-12-03 2021-01-26
273  130115 2021-02-01  MAP  Enrolled 2020-12-11 2021-01-25
276  140574 2021-02-01  MAP  Enrolled 2020-11-13 2021-01-28

                            Rep
72          Brad Willinger (BD)
106  Ivonne Cedeno Mendoza (BD)
117      Griselle Leonardo (BD)
171     Laura Lou Seefeldt (BD)
172      Katiria Fernandez (BD)
175      Katiria Fernandez (BD)
182      Griselle Leonardo (BD)
183       Carolina Zuluaga (BD)
185  Ivonne Cedeno Mendoza (BD)
207      Griselle Leonardo (BD)
209       Carolina Zuluaga (BD)
214  Ivonne Cedeno Mendoza (BD)
216      Katiria Fernandez (BD)
220      Griselle Leonardo (BD)
223      Katiria Fernandez (BD)
230  Ivonne Cedeno Mendoza (BD)
232  Ivonne Cedeno Mendoza (BD)
240      Griselle Leonardo (BD)
242      Griselle Leonardo (BD)
245      Griselle Leonardo (BD)
246      Griselle Leonardo (BD)
247  Ivonne Cedeno Mendoza (BD)
248  Ivonne Cedeno Mendoza (BD)
249  Ivonne Cedeno Mendoza (BD)
252  Ivonne Cedeno Mendoza (BD)
253      Griselle Leonardo (BD)
254            Shelly Bobb (BD)
257      Griselle Leonardo (BD)
258  Ivonne Cedeno Mendoza (BD)
261  Ivonne Cedeno Mendoza (BD)
262            Shelly Bobb (BD)
266      Griselle Leonardo (BD)
267      Griselle Leonardo (BD)
269  Ivonne Cedeno Mendoza (BD)
272  Ivonne Cedeno Mendoza (BD)
273      Griselle Leonardo (BD)
276      Katiria Fernandez (BD)

Enrolled
   LOB                         Rep  count
0  MAP         Brad Willinger (BD)      1
1  MAP       Carolina Zuluaga (BD)      2
2  MAP      Griselle Leonardo (BD)     13
3  MAP  Ivonne Cedeno Mendoza (BD)     13
4  MAP      Katiria Fernandez (BD)      5
5  MAP     Laura Lou Seefeldt (BD)      1
6  MAP            Shelly Bobb (BD)      2
total=
37

print(df4)
print()
print('Enrolled')
print (df4.groupby(["LOB", "Rep"])["Rep"].count().reset_index(name="count"))
print('total=')
print(df4.count().Rep)

import dataframe_image as dfi

dfi.export(df4, 'df4.jpg')

In [28]:
# https://datatofish.com/export-dataframe-to-excel/

# Withdrawl
df2.to_excel(r'Withdraw_AEP.xlsx', index = False)
df6.to_excel(r'Withdrawl_Count_AEP.xlsx', index = False)

# Not Enrolled
df3.to_excel(r'Notenrolled_AEP.xlsx', index = False)
df7.to_excel(r'Notenroll_Count_AEP.xlsx', index = False)

# Enrolled
df4.to_excel(r'Enrolled_AEP.xlsx', index = False)
df8.to_excel(r'Enrolled_Count_AEP.xlsx', index = False)