# Vines

In [7]:
import pandas as pd
import os

# DualEligibleMembers.xlsx
#pd.read_excel('DualEligibleMembers.xlsx', index_col=0)

#url = "S:\ENROLLMENT\ENROLLMENT-PUBLIC\MEDICARE\MAPD\MAPD&SNP Roster_2021.xlsx"

url = "C:\\Users\\tflung\\Downloads\\Demo Data Set - Lease Renewals.xlsx"

#url = "MAPD&SNP Roster_2021.xlsx"

df1=pd.read_excel(
     os.path.join(url),
     engine='openpyxl',
     sheet_name='Data'
     #skiprows = 2
)

#print (df1)

df2 = df1[['LeaseSignMonth', 'Market', 'LeaseRentDiffPercent']]

df2

      LeaseSignMonth      Market  LeaseRentDiffPercent
0         2018-03-01  Cincinnati                  0.03
1         2019-03-01  Cincinnati                  0.01
2         2019-02-01  Cincinnati                  0.03
3         2020-03-01  Cincinnati                  0.03
4         2018-01-01  Cincinnati                  0.03
...              ...         ...                   ...
35617     2021-07-01  Cincinnati                  0.13
35618     2021-10-01  Cincinnati                  0.09
35619     2019-08-01  Cincinnati                  0.00
35620     2020-09-01  Cincinnati                  0.04
35621     2018-08-01  Cincinnati                  0.03

[35622 rows x 3 columns]

In [15]:
df2.groupby(df2['LeaseSignMonth'].dt.strftime('%B %Y'))['LeaseRentDiffPercent'].mean().sort_values()

LeaseSignMonth
January 2021      0.012023
March 2021        0.012693
September 2019    0.012947
April 2021        0.013908
December 2019     0.016414
January 2018      0.022638
November 2019     0.023290
December 2020     0.025591
January 2020      0.026290
September 2020    0.027154
May 2021          0.027164
February 2018     0.027835
February 2021     0.028669
October 2019      0.032557
June 2020         0.032579
February 2020     0.033273
April 2020        0.033408
June 2021         0.033854
November 2020     0.034596
March 2020        0.036885
May 2020          0.037527
August 2020       0.037695
April 2019        0.038872
July 2020         0.039740
July 2018         0.039793
March 2019        0.040191
July 2019         0.040501
July 2021         0.040688
March 2018        0.041404
October 2020      0.041581
August 2019       0.042090
June 2018         0.043228
May 2019          0.043539
February 2019     0.044696
April 2018        0.047232
June 2019         0.048078
August 2021       0.048931
January 2019      0.049694
November 2021     0.051280
September 2021    0.052431
December 2018     0.053923
May 2018          0.054088
August 2018       0.054373
October 2021      0.059039
November 2018     0.061522
September 2018    0.064926
October 2018      0.065458
Name: LeaseRentDiffPercent, dtype: float64